#line 2 "sksiteconfig_lex.c"

#line 4 "sksiteconfig_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer sksiteconfig__create_buffer
#define yy_delete_buffer sksiteconfig__delete_buffer
#define yy_flex_debug sksiteconfig__flex_debug
#define yy_init_buffer sksiteconfig__init_buffer
#define yy_flush_buffer sksiteconfig__flush_buffer
#define yy_load_buffer_state sksiteconfig__load_buffer_state
#define yy_switch_to_buffer sksiteconfig__switch_to_buffer
#define yyin sksiteconfig_in
#define yyleng sksiteconfig_leng
#define yylex sksiteconfig_lex
#define yylineno sksiteconfig_lineno
#define yyout sksiteconfig_out
#define yyrestart sksiteconfig_restart
#define yytext sksiteconfig_text
#define yywrap sksiteconfig_wrap
#define yyalloc sksiteconfig_alloc
#define yyrealloc sksiteconfig_realloc
#define yyfree sksiteconfig_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE sksiteconfig_restart(sksiteconfig_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t sksiteconfig_leng;

extern FILE *sksiteconfig_in, *sksiteconfig_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up sksiteconfig_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up sksiteconfig_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via sksiteconfig_restart()), so that the user can continue scanning by
	 * just pointing sksiteconfig_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when sksiteconfig_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t sksiteconfig_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow sksiteconfig_wrap()'s to do buffer switches
 * instead of setting up a fresh sksiteconfig_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void sksiteconfig_restart (FILE *input_file  );
void sksiteconfig__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE sksiteconfig__create_buffer (FILE *file,int size  );
void sksiteconfig__delete_buffer (YY_BUFFER_STATE b  );
void sksiteconfig__flush_buffer (YY_BUFFER_STATE b  );
void sksiteconfig_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void sksiteconfig_pop_buffer_state (void );

static void sksiteconfig_ensure_buffer_stack (void );
static void sksiteconfig__load_buffer_state (void );
static void sksiteconfig__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER sksiteconfig__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE sksiteconfig__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE sksiteconfig__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE sksiteconfig__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *sksiteconfig_alloc (yy_size_t  );
void *sksiteconfig_realloc (void *,yy_size_t  );
void sksiteconfig_free (void *  );

#define yy_new_buffer sksiteconfig__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        sksiteconfig_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            sksiteconfig__create_buffer(sksiteconfig_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        sksiteconfig_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            sksiteconfig__create_buffer(sksiteconfig_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *sksiteconfig_in = (FILE *) 0, *sksiteconfig_out = (FILE *) 0;

typedef int yy_state_type;

extern int sksiteconfig_lineno;

int sksiteconfig_lineno = 1;

extern char *sksiteconfig_text;
#define yytext_ptr sksiteconfig_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up sksiteconfig_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	sksiteconfig_leng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[143] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   41,   19,
        1,    3,   19,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   27,   21,   23,   26,   27,   25,   24,
       40,   20,   39,   29,   28,   40,    1,    0,    2,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   21,
        0,   22,   25,   24,    0,   20,   39,   38,   37,   30,
       31,   35,   36,   32,   34,   33,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   30,   31,   18,   18,
        0,   18,   18,   18,   18,   18,   16,   18,   30,    4,
       18,    9,    9,    9,   10,   18,   18,   18,   18,   18,

       18,    9,    9,   18,   18,   18,   14,   18,   18,    9,
        9,   11,   18,   18,   15,   17,   18,    9,    9,   18,
       18,   18,   18,    7,    8,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   12,   18,   18,   18,    5,    6,
       13,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    9,    9,    1,    1,    1,
        1,    1,    1,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        1,   10,    1,    1,    7,    1,   11,   12,   13,   14,

       15,   16,   17,   18,   19,    7,   20,   21,   22,   23,
       24,   25,    7,   26,   27,   28,   29,   30,    7,    7,
       31,    7,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[32] =
    {   0,
        1,    2,    3,    3,    1,    4,    4,    4,    4,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4
    } ;

static yyconst flex_int16_t yy_base[154] =
    {   0,
        0,    0,   31,   41,  212,  211,   44,   49,  213,  216,
      210,  216,  208,    0,  189,  194,  185,  181,  183,  194,
      189,  172,  187,  216,  199,  216,  216,  197,    0,   29,
      196,  216,    0,  216,  216,   57,  196,  194,  216,    0,
      185,  179,  180,  169,  179,   42,  168,  165,  163,  186,
      184,  216,    0,   48,  183,  216,    0,  216,  216,   53,
       55,  216,  216,  216,  216,  216,  158,  173,  181,  153,
      160,  160,  161,  151,  162,  149,   59,   63,  148,  145,
       73,  148,  143,  152,  164,  145,    0,  149,   68,    0,
      146,  164,   72,   56,    0,  151,  141,  147,  136,  137,

      132,   76,   77,  144,  141,  133,  129,  132,  148,   79,
       82,    0,  147,  126,    0,    0,   75,   87,   90,  130,
      127,  121,   82,  110,  108,   85,   97,   96,   80,   87,
       74,   73,   84,   79,    0,   70,   69,   82,    0,    0,
        0,  216,  115,  119,  123,  127,   90,  131,   87,  135,
      139,  143,  146
    } ;

static yyconst flex_int16_t yy_def[154] =
    {   0,
      142,    1,  143,  143,  144,  144,  145,  145,  142,  142,
      142,  142,  146,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  142,  142,  142,  142,  148,  149,  149,
      150,  142,  151,  142,  142,  152,  142,  146,  142,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  142,
      148,  142,  149,  149,  150,  142,  151,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  142,  142,  147,  147,
      153,  147,  147,  147,  147,  147,  147,  147,  142,  147,
      147,  153,  153,  153,  147,  147,  147,  147,  147,  147,

      147,  153,  153,  147,  147,  147,  147,  147,  147,  153,
      153,  147,  147,  147,  147,  147,  147,  153,  153,  147,
      147,  147,  147,  153,  153,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,    0,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142
    } ;

static yyconst flex_int16_t yy_nxt[248] =
    {   0,
       10,   11,   12,   10,   13,   14,   14,   14,   14,   10,
       14,   14,   15,   16,   17,   14,   18,   14,   19,   14,
       14,   14,   14,   14,   20,   14,   21,   22,   14,   23,
       14,   24,   25,   26,   27,   28,   54,   54,   30,   30,
       24,   24,   25,   26,   27,   28,   34,   35,   30,   30,
       24,   34,   35,   36,   72,   54,   54,  142,   36,   59,
       77,   78,   78,   78,   60,   61,   89,   78,   62,   73,
       78,   78,   63,  142,   81,   78,   78,  142,  142,   64,
      142,  103,   65,  142,   66,   93,  110,  122,  142,   94,
       53,  142,  102,   40,  141,  140,  139,  138,  137,  136,

      111,  135,  123,  134,  133,  118,  132,  131,  130,  142,
      119,  142,  129,  124,  125,   29,   29,   29,   29,   31,
       31,   31,   31,   33,   33,   33,   33,   38,   38,   38,
       38,   51,   51,   51,   51,   55,   55,   55,   55,   57,
       57,  128,   57,   58,   58,   58,   58,   92,  127,   92,
      126,  121,  120,  117,  116,  115,  114,  113,  112,  109,
      108,  107,  106,  105,  104,  142,  101,  100,   99,   98,
       97,   96,   95,   91,   90,   88,   87,   86,   85,   84,
       83,   82,   81,   80,   79,   56,   52,   50,   76,   75,
       74,   71,   70,   69,   68,   67,   39,   37,   56,   52,

       50,   49,   48,   47,   46,   45,   44,   43,   42,   41,
       39,   37,  142,   32,   32,    9,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142
    } ;

static yyconst flex_int16_t yy_chk[248] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,   30,   30,    3,    3,
        3,    4,    4,    4,    4,    4,    7,    7,    4,    4,
        4,    8,    8,    7,   46,   54,   54,   94,    8,   36,
       60,   60,   61,   61,   36,   36,   77,   77,   36,   46,
       78,   78,   36,   93,   81,   89,   89,  102,  103,   36,
      110,   94,   36,  111,   36,   81,  102,  117,  118,   81,
      149,  119,   93,  147,  138,  137,  136,  134,  133,  132,

      103,  131,  117,  130,  129,  110,  128,  127,  126,  125,
      111,  124,  123,  118,  119,  143,  143,  143,  143,  144,
      144,  144,  144,  145,  145,  145,  145,  146,  146,  146,
      146,  148,  148,  148,  148,  150,  150,  150,  150,  151,
      151,  122,  151,  152,  152,  152,  152,  153,  121,  153,
      120,  114,  113,  109,  108,  107,  106,  105,  104,  101,
      100,   99,   98,   97,   96,   92,   91,   88,   86,   85,
       84,   83,   82,   80,   79,   76,   75,   74,   73,   72,
       71,   70,   69,   68,   67,   55,   51,   50,   49,   48,
       47,   45,   44,   43,   42,   41,   38,   37,   31,   28,

       25,   23,   22,   21,   20,   19,   18,   17,   16,   15,
       13,   11,    9,    6,    5,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int sksiteconfig__flex_debug;
int sksiteconfig__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *sksiteconfig_text;
#line 1 "sksiteconfig_lex.l"
#line 2 "sksiteconfig_lex.l"
/*
** Copyright (C) 2006-2020 by Carnegie Mellon University.
**
** @OPENSOURCE_LICENSE_START@
** See license information in ../../LICENSE.txt
** @OPENSOURCE_LICENSE_END@
*/

/*
**  Tokenizer for silk toolset configuration file.
**
*/

#include <silk/silk.h>

RCSIDENT("$SiLK: sksiteconfig_lex.l ef14e54179be 2020-04-14 21:57:45Z mthomas $");

#include "sksiteconfig.h"
#include "sksiteconfig_parse.h"
#include <silk/utils.h>


typedef struct sksiteconfig_file_st {
    YY_BUFFER_STATE state;
    char           *name;
    FILE           *fp;
    int             line;
} sksiteconfig_file_t;

/* EXPORTED VARIABLES */

/* LOCAL VARIABLES */

/* count the number of errors that have occurred during processing */
static int sksiteconfig_errors = 0;

/* support for "include" */
static sksiteconfig_file_t sksiteconfig_stack[SKSITECONFIG_MAX_INCLUDE_DEPTH];

/* next stack position */
static int sksiteconfig_stack_depth = 0;

/* current pointer into sksiteconfig_stack[] */
static sksiteconfig_file_t *sksiteconfig_file = NULL;

/* local buffer for reading quoted strings */
#define BUF_SIZE 2048
static char sksiteconfig_buf[BUF_SIZE];
static char *sksiteconfig_buf_end = sksiteconfig_buf + BUF_SIZE - 1;
static char *sksiteconfig_buf_ptr;

/* Macros for checking that we're not overflowing the buffer, returning
 * a string, and appending a single character to a string. */

#define STRING_CHECK                                            \
    if ( sksiteconfig_buf_ptr >= sksiteconfig_buf_end ) {       \
        BEGIN(ST_ERR);                                          \
        return ERR_STR_TOO_LONG;                                \
    }

#define STRING_RETURN                           \
    sksiteconfig_buf_ptr = '\0';                \
    yylval.str = strdup(sksiteconfig_buf);      \
    return TOK_STRING;

#define STRING_APPEND(x) (*sksiteconfig_buf_ptr++ = (x))

SK_DIAGNOSTIC_IGNORE_PUSH("-Wwrite-strings")

#define YY_NO_INPUT 1
/* %option noyyget_extra noyyset_extra noyyget_leng noyyget_text */
/* %option noyyget_lineno noyyset_lineno noyyget_in noyyset_in */
/* %option noyyget_out noyyset_out noyyget_lval noyyset_lval */
/* %option noyyget_lloc noyyset_lloc noyyget_debug noyyset_debug */
/* The INITIAL state is used for top-level commands */
/* The ST_ARGS state is for processing arguments to commands */

/* The ST_ERR state is for error recovery, ignores everything to EOL */

/* The ST_STRING state is for consuming quoted strings */

/* Whitespace (to be ignored) */
/* Atoms (symbols) without quotes */
/* Integral numbers (value returned to parser as a string) */
/* End of line: command separator */
#line 658 "sksiteconfig_lex.c"

#define INITIAL 0
#define ST_ARGS 1
#define ST_ERR 2
#define ST_STRING 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int sksiteconfig_lex_destroy (void );

int sksiteconfig_get_debug (void );

void sksiteconfig_set_debug (int debug_flag  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int sksiteconfig_wrap (void );
#else
extern int sksiteconfig_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( sksiteconfig_text, sksiteconfig_leng, 1, sksiteconfig_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( sksiteconfig_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( sksiteconfig_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, sksiteconfig_in))==0 && ferror(sksiteconfig_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(sksiteconfig_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int sksiteconfig_lex (void);

#define YY_DECL int sksiteconfig_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after sksiteconfig_text and sksiteconfig_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 108 "sksiteconfig_lex.l"


    /* INITIAL state: Throw away comments, whitespace.  Treat any atom
       as a command name, plus "end <atom>".  Valid commands are returned
       as specific tokens.  Unknown commands are returned as strings for
       error reporting purposes.  Anything else implies the whole line
       cannot be interpreted, and enters the ST_ERR state to clear out
       everything to the EOL.  After a valid command, enter the ST_ARGS
       state for argument parsing. */

#line 832 "sksiteconfig_lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! sksiteconfig_in )
			sksiteconfig_in = stdin;

		if ( ! sksiteconfig_out )
			sksiteconfig_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			sksiteconfig_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				sksiteconfig__create_buffer(sksiteconfig_in,YY_BUF_SIZE );
		}

		sksiteconfig__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of sksiteconfig_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 143 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 142 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 118 "sksiteconfig_lex.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 119 "sksiteconfig_lex.l"
{ ++sksiteconfig_file->line; return TOK_NL; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 120 "sksiteconfig_lex.l"
{ ++sksiteconfig_file->line; return TOK_NL; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 121 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_CLASS; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 122 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_DEF_CLASS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 123 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_DEF_TYPES; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 124 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_END_CLASS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 125 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_END_GROUP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 126 "sksiteconfig_lex.l"
{ yylval.str = strdup(sksiteconfig_text);
                          BEGIN(ST_ERR);  return ERR_UNK_CMD; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 128 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_GROUP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 129 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_INCLUDE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 130 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_PATH_FORMAT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 131 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_PACKING_LOGIC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 132 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_SENSOR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 133 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_SENSORS; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_TYPE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); return TOK_VERSION; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 136 "sksiteconfig_lex.l"
{ yylval.str = strdup(sksiteconfig_text);
                          BEGIN(ST_ERR);  return ERR_UNK_CMD; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 138 "sksiteconfig_lex.l"
{ BEGIN(ST_ERR);  return ERR_UNREC; }
	YY_BREAK
/* ST_ERR state: Throw away everything up to the newline, because we've
       seen something we're unable to interpret. */
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 143 "sksiteconfig_lex.l"
{ BEGIN(INITIAL); ++sksiteconfig_file->line;
                          return TOK_NL; }
	YY_BREAK
/* ST_ARGS state: Ignore whitespace as usual, at a newline or comment,
       return back to the INITIAL state.  Atoms, integers, and quoted
       strings are all valid input in this state. */
case 21:
YY_RULE_SETUP
#line 150 "sksiteconfig_lex.l"
;
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 151 "sksiteconfig_lex.l"
{ BEGIN(INITIAL); ++sksiteconfig_file->line;
                          return TOK_NL; }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 153 "sksiteconfig_lex.l"
{ BEGIN(INITIAL); ++sksiteconfig_file->line;
                          return TOK_NL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 155 "sksiteconfig_lex.l"
{ yylval.str = strdup(sksiteconfig_text); return TOK_INTEGER; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 156 "sksiteconfig_lex.l"
{ yylval.str = strdup(sksiteconfig_text); return TOK_ATOM; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 157 "sksiteconfig_lex.l"
{ BEGIN(ST_STRING);
                          sksiteconfig_buf_ptr = sksiteconfig_buf; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 159 "sksiteconfig_lex.l"
{ BEGIN(ST_ERR);  return ERR_UNREC; }
	YY_BREAK
/* ST_STRING state: Accepts the remainder of a quoted string (after the
       initial quote) and returns the value.  This is pretty much equivalent
       to quoted strings in C. */
case 28:
YY_RULE_SETUP
#line 165 "sksiteconfig_lex.l"
{ BEGIN(ST_ARGS); STRING_CHECK;
                          *sksiteconfig_buf_ptr = '\0';
                          yylval.str = strdup(sksiteconfig_buf);
                          return TOK_STRING; }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 170 "sksiteconfig_lex.l"
{ BEGIN(INITIAL); ++sksiteconfig_file->line;
                          return ERR_UNTERM_STRING; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 173 "sksiteconfig_lex.l"
{ unsigned int oct_char;
                          STRING_CHECK;
                          (void) sscanf(sksiteconfig_text+1, "%o", &oct_char);
                          if ( oct_char > 0xff ) {
                              BEGIN(ST_ERR);
                              return ERR_INVALID_OCTAL_ESCAPE;
                          };
                          *sksiteconfig_buf_ptr++ = oct_char; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 182 "sksiteconfig_lex.l"
{ BEGIN(ST_ERR); return ERR_INVALID_OCTAL_ESCAPE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 184 "sksiteconfig_lex.l"
{ STRING_CHECK; *sksiteconfig_buf_ptr++ = '\n'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 185 "sksiteconfig_lex.l"
{ STRING_CHECK; *sksiteconfig_buf_ptr++ = '\t'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 186 "sksiteconfig_lex.l"
{ STRING_CHECK; *sksiteconfig_buf_ptr++ = '\r'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 187 "sksiteconfig_lex.l"
{ STRING_CHECK; *sksiteconfig_buf_ptr++ = '\b'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 188 "sksiteconfig_lex.l"
{ STRING_CHECK; *sksiteconfig_buf_ptr++ = '\f'; }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 189 "sksiteconfig_lex.l"
{ STRING_CHECK; *sksiteconfig_buf_ptr++ = '\n'; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 190 "sksiteconfig_lex.l"
{ STRING_CHECK; *sksiteconfig_buf_ptr++ = sksiteconfig_text[1]; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 192 "sksiteconfig_lex.l"
{ if ( (sksiteconfig_buf_ptr + sksiteconfig_leng) >
                                       sksiteconfig_buf_end ) {
                              BEGIN(ST_ERR);
                              return ERR_STR_TOO_LONG;
                          };
                          memcpy(sksiteconfig_buf_ptr, sksiteconfig_text, sksiteconfig_leng);
                          sksiteconfig_buf_ptr += sksiteconfig_leng; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 200 "sksiteconfig_lex.l"
ECHO;
	YY_BREAK
#line 1149 "sksiteconfig_lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ST_ARGS):
case YY_STATE_EOF(ST_ERR):
case YY_STATE_EOF(ST_STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed sksiteconfig_in at a new source and called
			 * sksiteconfig_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = sksiteconfig_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( sksiteconfig_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * sksiteconfig_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of sksiteconfig_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					sksiteconfig_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			sksiteconfig_restart(sksiteconfig_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) sksiteconfig_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 143 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 143 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 142);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					sksiteconfig_restart(sksiteconfig_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( sksiteconfig_wrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve sksiteconfig_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void sksiteconfig_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        sksiteconfig_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            sksiteconfig__create_buffer(sksiteconfig_in,YY_BUF_SIZE );
	}

	sksiteconfig__init_buffer(YY_CURRENT_BUFFER,input_file );
	sksiteconfig__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void sksiteconfig__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		sksiteconfig_pop_buffer_state();
	 *		sksiteconfig_push_buffer_state(new_buffer);
     */
	sksiteconfig_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	sksiteconfig__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (sksiteconfig_wrap()) processing, but the only time this flag
	 * is looked at is after sksiteconfig_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void sksiteconfig__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	sksiteconfig_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE sksiteconfig__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) sksiteconfig_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in sksiteconfig__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) sksiteconfig_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in sksiteconfig__create_buffer()" );

	b->yy_is_our_buffer = 1;

	sksiteconfig__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with sksiteconfig__create_buffer()
 * 
 */
    void sksiteconfig__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		sksiteconfig_free((void *) b->yy_ch_buf  );

	sksiteconfig_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a sksiteconfig_restart() or at EOF.
 */
    static void sksiteconfig__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	sksiteconfig__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then sksiteconfig__init_buffer was _probably_
     * called from sksiteconfig_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void sksiteconfig__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		sksiteconfig__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void sksiteconfig_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	sksiteconfig_ensure_buffer_stack();

	/* This block is copied from sksiteconfig__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from sksiteconfig__switch_to_buffer. */
	sksiteconfig__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void sksiteconfig_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	sksiteconfig__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		sksiteconfig__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void sksiteconfig_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)sksiteconfig_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in sksiteconfig_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)sksiteconfig_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in sksiteconfig_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE sksiteconfig__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) sksiteconfig_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in sksiteconfig__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	sksiteconfig__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to sksiteconfig_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       sksiteconfig__scan_bytes() instead.
 */
YY_BUFFER_STATE sksiteconfig__scan_string (yyconst char * yystr )
{
    
	return sksiteconfig__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to sksiteconfig_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE sksiteconfig__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) sksiteconfig_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in sksiteconfig__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = sksiteconfig__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in sksiteconfig__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up sksiteconfig_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		sksiteconfig_text[sksiteconfig_leng] = (yy_hold_char); \
		(yy_c_buf_p) = sksiteconfig_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		sksiteconfig_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current token.
 * 
 */

int sksiteconfig_get_debug  (void)
{
        return sksiteconfig__flex_debug;
}

void sksiteconfig_set_debug (int  bdebug )
{
        sksiteconfig__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from sksiteconfig_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    sksiteconfig_in = stdin;
    sksiteconfig_out = stdout;
#else
    sksiteconfig_in = (FILE *) 0;
    sksiteconfig_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * sksiteconfig_lex_init()
     */
    return 0;
}

/* sksiteconfig_lex_destroy is for both reentrant and non-reentrant scanners. */
int sksiteconfig_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		sksiteconfig__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		sksiteconfig_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	sksiteconfig_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * sksiteconfig_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *sksiteconfig_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *sksiteconfig_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void sksiteconfig_free (void * ptr )
{
	free( (char *) ptr );	/* see sksiteconfig_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "sksiteconfig_lex.l"



SK_DIAGNOSTIC_IGNORE_POP("-Wwrite-strings")

int
sksiteconfig_wrap(void)
{
    return sksiteconfigIncludePop();
}


/* Report an error while parsing (printf style) */
#ifndef sksiteconfigErr
void
sksiteconfigErr(
    const char         *fmt,
    ...)
{
    va_list ap;

    va_start(ap, fmt);
    fprintf(stderr, "%s: Error while parsing site configuration file",
            skAppName());
    if (sksiteconfig_file != NULL && sksiteconfig_file->name != NULL) {
        fprintf(stderr, " at %s:%d",
                sksiteconfig_file->name, sksiteconfig_file->line);
    }
    fprintf(stderr, ":\n\t");
    vfprintf(stderr, fmt, ap);
    fprintf(stderr, "\n");
    ++sksiteconfig_errors;
    va_end(ap);
}
#endif /* sksiteconfigErr() */


int
sksiteconfigIncludePop(
    void)
{
    /*  if depth is 0, we are done */
    if ( sksiteconfig_stack_depth == 0 ) {
        return 1;
    }

    /* clean up current state */
    sksiteconfig__delete_buffer(YY_CURRENT_BUFFER);
    fclose(sksiteconfig_file->fp);
    free(sksiteconfig_file->name);

    /* go to the previous state; if depth is 0, we are done */
    --sksiteconfig_stack_depth;
    if ( sksiteconfig_stack_depth == 0 ) {
        sksiteconfig_file = NULL;
        return 1;
    }
    sksiteconfig_file = &(sksiteconfig_stack[sksiteconfig_stack_depth-1]);
    sksiteconfig__switch_to_buffer(sksiteconfig_file->state);

    /* let processing continue */
    return 0;
}

static int
sksiteconfigOpenFile(
    char               *filename,
    int                 verbose_error)
{
    sksiteconfig_file_t *new_file;
    const char *action_name = ((sksiteconfig_stack_depth == 0)
                               ? "read config"
                               : "include");

    if (filename == NULL) {
        return -1;
    }

    if (!skFileExists(filename)) {
        if (!verbose_error) {
            /* be silent */
        } else if (0 == sksiteconfig_stack_depth) {
            skAppPrintErr(("Cannot %s '%s': "
                           "File does not exist or is not a regular file"),
                          action_name, filename);
        } else {
            sksiteconfigErr(("Cannot %s '%s': "
                             "File does not exist or is not a regular file"),
                            action_name, filename);
        }
        goto ERROR;
    }

    if (sksiteconfig_stack_depth >= SKSITECONFIG_MAX_INCLUDE_DEPTH) {
        sksiteconfigErr("Failed to %s file '%s' (includes nested too deeply)",
                        action_name, filename);
        goto ERROR;
    }

    new_file = &sksiteconfig_stack[sksiteconfig_stack_depth];
    new_file->name = filename;
    new_file->line = 0;

    /* open the file */
    new_file->fp = fopen(new_file->name, "r");
    if ( !new_file->fp) {
        if (verbose_error) {
            sksiteconfigErr("Failed to %s file '%s' (%s)",
                            action_name, new_file->name, strerror(errno));
        }
        goto ERROR;
    }

    new_file->state = sksiteconfig__create_buffer(new_file->fp,YY_BUF_SIZE);
    sksiteconfig__switch_to_buffer(new_file->state);

    /* success */
    sksiteconfig_file = new_file;
    ++sksiteconfig_stack_depth;
    BEGIN(INITIAL);

    return 0;

  ERROR:
    if (filename) {
        free(filename);
    }
    return -1;
}


void
sksiteconfigIncludePush(
    char               *filename)
{
    (void)sksiteconfigOpenFile(filename, 1);
}

int
sksiteconfigParse(
    const char         *filename,
    int                 verbose)
{
    const char *env;

    env = getenv("SKSITECONFIG_TESTING");
    if (env && !(*env == '\0' || *env == '0')) {
        sksiteconfig_testing = 1;
    }

    sksiteconfig_stack_depth = 0;
    if (sksiteconfigOpenFile(strdup(filename), verbose)) {
        return -1;
    }

    (void)yyparse();

    if ( sksiteconfig_errors > 0 ) {
        return -1;
    } else {
        return 0;
    }
}


/*
** Local variables:
** mode:c
** indent-tabs-mode:nil
** c-basic-offset:4
** End:
*/

